---
detectors:
  BooleanParameter:
    exclude:
      - "ActiveRecord::KSUID#self.[]"
      - "KSUID::ActiveRecord#self.[]"

  ControlParameter:
    exclude:
      - "ActiveRecord::KSUID#self.[]"
      - "ActiveRecord::KSUID#self.define_attribute"

  ManualDispatch:
    exclude:
      - "KSUID::Configuration#assert_generator_is_callable"

  UncommunicativeModuleName:
    exclude:
      - "KSUID::Base62"

  UncommunicativeMethodName:
    exclude:
      - "KSUID#self.from_base62"

  UtilityFunction:
    exclude:
      - "ActiveRecord::KSUID::BinaryType"
      - "ActiveRecord::KSUID::Type"

exclude_paths:
  - benchmark/

# vim: ft=yaml
